//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarOwnership
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.OwnershipHistories = new HashSet<OwnershipHistory>();
            this.ServiceHistories = new HashSet<ServiceHistory>();
        }
    
        public string pkCarRegistrationNumber { get; set; }
        public string model { get; set; }
        public int yearManufactured { get; set; }
        public string color { get; set; }
        public string engineType { get; set; }
        public int fkManufacturerID { get; set; }
    
        public virtual CarManufacturer CarManufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OwnershipHistory> OwnershipHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceHistory> ServiceHistories { get; set; }
    }
}
