//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarOwnership
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarOwner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarOwner()
        {
            this.OwnershipHistories = new HashSet<OwnershipHistory>();
        }
    
        public int pkOwnerID { get; set; }
        public string ownerName { get; set; }
        public System.DateTime dateOfBirthOrEstablishment { get; set; }
        public string contactNumber { get; set; }
        public string email { get; set; }
        public string streetAddress { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OwnershipHistory> OwnershipHistories { get; set; }
    }
}
