//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarOwnership
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnershipHistory
    {
        public int pkHistoryID { get; set; }
        public System.DateTime datePurchased { get; set; }
        public Nullable<System.DateTime> dateSold { get; set; }
        public string fkCarRegistrationNumber { get; set; }
        public int fkOwnerID { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual CarOwner CarOwner { get; set; }
    }
}
