//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarOwnership
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceHistory
    {
        public int pkServiceHistoryID { get; set; }
        public System.DateTime serviceDate { get; set; }
        public string serviceDescription { get; set; }
        public string fkCarRegistrationNumber { get; set; }
        public int fkServiceCenterID { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual ServiceCenter ServiceCenter { get; set; }
    }
}
