//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarOwnership
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceEmployee
    {
        public int pkEmployeeID { get; set; }
        public string employeeName { get; set; }
        public string position { get; set; }
        public string dateHired { get; set; }
        public int fkServiceCenterID { get; set; }
    
        public virtual ServiceCenter ServiceCenter { get; set; }
    }
}
